import { expect, test, type Locator } from '@playwright/test'
import { execFileSync, spawn, type ChildProcess } from 'node:child_process'
import { constants } from 'node:fs'
import { access, mkdir, mkdtemp, readFile, realpath, rename, rm, stat, symlink, writeFile } from 'node:fs/promises'
import { createServer } from 'node:net'
import { tmpdir } from 'node:os'
import { delimiter, isAbsolute, join, resolve } from 'node:path'
import type { AgentStatus } from '../shared/protocol'

function shellQuote(value: string) {
  return `'${value.replace(/'/g, "'\\''")}'`
}

async function findTmux(home: string): Promise<string> {
  const override = process.env.COMMANDO_CURSOR_TEST_TMUX
  if (override !== undefined && !isAbsolute(override)) {
    throw new Error('COMMANDO_CURSOR_TEST_TMUX must be an absolute executable path')
  }
  const candidates = override === undefined
    ? (process.env.PATH ?? '').split(delimiter).filter(isAbsolute).map((directory) => join(directory, 'tmux'))
    : [override]
  for (const candidate of [...new Set(candidates)]) {
    try {
      const executable = await realpath(candidate)
      await access(executable, constants.X_OK)
      if (!(await stat(executable)).isFile()) continue
      // Probe only version output, never a server. Skip PATH shims that cannot
      // run with the same isolated HOME used by the daemon and generated hooks.
      const version = execFileSync(executable, ['-V'], {
        env: { HOME: home, PATH: process.env.PATH, LANG: 'C' },
        encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 5_000, maxBuffer: 4_096,
      })
      if (/^tmux\s+\d/.test(version)) return executable
    } catch { /* Try the next absolute PATH entry, without invoking a shell. */ }
  }
  throw new Error('No working tmux executable found. Install tmux on PATH or set COMMANDO_CURSOR_TEST_TMUX to its absolute path.')
}

async function freePort() {
  const server = createServer()
  await new Promise<void>((done) => server.listen(0, '127.0.0.1', done))
  const address = server.address()
  if (!address || typeof address === 'string') throw new Error('Missing acceptance port')
  await new Promise<void>((done) => server.close(() => done()))
  return address.port
}

async function stop(child: ChildProcess) {
  if (child.exitCode !== null || child.signalCode !== null) return
  const exited = new Promise<void>((done) => child.once('exit', () => done()))
  child.kill('SIGTERM')
  const timer = setTimeout(() => child.kill('SIGKILL'), 5_000)
  try { await exited } finally { clearTimeout(timer) }
}

async function fitsViewport(control: Locator) {
  await control.scrollIntoViewIfNeeded()
  await expect(control).toBeVisible()
  expect(await control.evaluate((element) => {
    const box = element.getBoundingClientRect()
    let fits = box.width > 0 && box.height > 0 && box.left >= 0 && box.right <= innerWidth && box.top >= 0 && box.bottom <= innerHeight
    for (let parent = element.parentElement; parent; parent = parent.parentElement) {
      const style = getComputedStyle(parent)
      const bounds = parent.getBoundingClientRect()
      if (/(auto|scroll|hidden|clip)/.test(style.overflowX)) fits &&= box.left >= bounds.left - 1 && box.right <= bounds.right + 1
      if (/(auto|scroll|hidden|clip)/.test(style.overflowY)) fits &&= box.top >= bounds.top - 1 && box.bottom <= bounds.bottom + 1
    }
    return fits
  })).toBe(true)
}

// This is synthetic Cursor telemetry, not an authenticated Cursor/model run.
// The CLI is launched only by the real web form -> daemon -> tmux path. Native
// payloads go through the installed bridge, generated by a separate real tsx process.
test('synthetic Cursor CLI launches in a real pane, reports honest lifecycle, resumes without Enter, and preflights missing CLI', async ({ page, context }, testInfo) => {
  test.setTimeout(120_000)
  const root = await realpath(await mkdtemp(join(tmpdir(), 'cursor-session-acceptance-')))
  const home = join(root, 'home')
  const bin = join(root, 'bin')
  const cwd = join(root, 'synthetic workspace')
  const runtime = join(root, 'cursor-agent', 'index.js')
  const shots = join(root, 'screenshots')
  for (const directory of [home, bin, cwd, shots, join(root, 'cursor-agent')]) await mkdir(directory)
  const socket = `commando-cursor-acceptance-${process.pid}-${Date.now()}`
  const daemonPort = await freePort()
  const webPort = await freePort()
  const token = 'synthetic-cursor-acceptance-only'
  const baseUrl = `http://127.0.0.1:${webPort}`
  const tmuxBinary = await findTmux(home).catch(async (error) => {
    await rm(root, { recursive: true, force: true })
    throw error
  })
  await symlink(process.execPath, join(bin, 'node'))
  await symlink(tmuxBinary, join(bin, 'tmux'))
  // Deliberately whitelist environment instead of inheriting real credentials,
  // profiles, tokens, state directories, socket selectors, or shell startup files.
  const env: NodeJS.ProcessEnv = {
    HOME: home, USER: 'cursor-acceptance', LOGNAME: 'cursor-acceptance',
    PATH: [bin, '/usr/bin', '/bin', '/usr/sbin', '/sbin'].join(delimiter), SHELL: '/bin/sh',
    // Keep tmux's snapshot separators/terminal Unicode intact in an isolated
    // UTF-8 locale. Ownership's ps timestamps independently use LC_ALL=C.
    LANG: process.platform === 'darwin' ? 'en_US.UTF-8' : 'C.UTF-8',
    TMPDIR: root, XDG_CONFIG_HOME: join(home, '.config'),
    CLAUDE_CONFIG_DIR: join(home, '.claude-profile'), CODEX_HOME: join(home, '.codex-profile'),
    CURSOR_CONFIG_DIR: join(home, '.cursor-profile'),
    COMMANDO_AGENT_HOOK_TOKEN_PATH: join(home, '.commando', 'agent-hook-token'),
    COMMANDO_PORT: String(daemonPort), COMMANDO_TOKEN: token,
    COMMANDO_OWNER_EMAIL: '', COMMANDO_TMUX_SOCKET_NAME: socket,
  }
  const children: ChildProcess[] = []
  const childErrors = new Map<ChildProcess, string>()
  const failures: string[] = []
  const statusFrames: Array<{ type: string; status?: AgentStatus }> = []
  const tmux = (...args: string[]) => execFileSync(tmuxBinary, ['-L', socket, ...args], {
    env, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 5_000,
  }).trim()
  const start = (args: string[]) => {
    const child = spawn(process.execPath, args, { cwd: resolve('.'), env, stdio: ['ignore', 'pipe', 'pipe'] })
    // Never retain stdout (the daemon prints its token). Bound stderr and redact
    // credentials so a startup failure is diagnosable without unbounded logs.
    child.stdout?.resume()
    child.stderr?.on('data', (chunk) => {
      childErrors.set(child, ((childErrors.get(child) ?? '') + String(chunk))
        .replaceAll(token, '[fixture token]')
        .replace(/\b[a-f0-9]{32,}\b/gi, '[redacted identifier]')
        .slice(-4_096))
    })
    children.push(child)
    return child
  }
  const snapshot = async () => {
    const response = await fetch(`${baseUrl}/api/snapshot`, { headers: { Authorization: `Bearer ${token}` } })
    if (!response.ok) throw new Error(`Isolated snapshot returned ${response.status}`)
    return response.json()
  }
  const fixtureState = async () => JSON.parse(await readFile(join(home, 'fixture-state.json'), 'utf8'))
  const input = async () => { try { return await readFile(join(home, 'fixture-input.txt'), 'utf8') } catch { return '' } }
  let presentation: { id: string; origin: string; token: string } | undefined
  let passed = false
  try {
    // Import with the same real tsx path used by the daemon. Playwright's own
    // transform must not conceal standalone generated-JS helper dependencies.
    const installerModule = resolve('server/agent-hook-installer.ts')
    execFileSync(process.execPath, ['--import', 'tsx', '--input-type=module', '-e',
      `const { AgentHookInstaller } = await import(${JSON.stringify(installerModule)}); await new AgentHookInstaller({home: process.env.HOME}).install();`,
    ], { env, cwd: resolve('.'), stdio: ['ignore', 'ignore', 'pipe'], timeout: 20_000 })
    // Match the native CLI's supported foreground process shape so production
    // ownership checks really execute; do not bypass or mock association checks.
    await writeFile(join(bin, 'agent'), `#!/bin/sh\nexec ${shellQuote(process.execPath)} ${shellQuote(runtime)} "$@"\n`, { mode: 0o755 })
    await writeFile(runtime, `
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const home = process.env.HOME;
const state = {pid: process.pid, ppid: process.ppid, stdinTTY: !!process.stdin.isTTY, stdoutTTY: !!process.stdout.isTTY,
  argv: process.argv.slice(2), pane: process.env.TMUX_PANE, cwd: process.cwd(), port: process.env.COMMANDO_PORT,
  home, cursorProfile: process.env.CURSOR_CONFIG_DIR, claudeProfile: process.env.CLAUDE_CONFIG_DIR, codexProfile: process.env.CODEX_HOME,
  tokenPath: process.env.COMMANDO_AGENT_HOOK_TOKEN_PATH, socket: process.env.COMMANDO_TMUX_SOCKET_NAME, hooks: []};
const save = () => fs.writeFileSync(path.join(home, 'fixture-state.json'), JSON.stringify(state));
const hooks = JSON.parse(fs.readFileSync(path.join(home, '.cursor/hooks.json'), 'utf8')).hooks;
let generation = 'gen-1';
function hook(event, patch = {}) {
  const payload = {hook_event_name: event, conversation_id: 'conv-synthetic-acceptance', cursor_version: 'synthetic-2026.10.01',
    ...(event === 'sessionStart' || event === 'sessionEnd' ? {} : {generation_id: generation}), ...patch};
  const stdout = execFileSync('/bin/sh', ['-c', hooks[event][0].command], {input: JSON.stringify(payload), encoding: 'utf8', timeout: 5000});
  state.hooks.push({event, response: JSON.parse(stdout)}); save();
}
if (!process.stdin.isTTY || !process.stdout.isTTY) throw new Error('Synthetic CLI must run in a real pane tty');
save();
console.log('SYNTHETIC CURSOR CLI FIXTURE — no live model/authentication');
async function main() {
  // tmux starts a pane before the create response refreshes the daemon snapshot.
  // Wait until that snapshot observes the exec'd Node producer, not its initial
  // shell, so this controlled fixture cannot race shell-to-agent reconciliation.
  // Never invent a delay or replay sessionStart to recover a rejected stream.
  let registered = false;
  for (let attempt = 0; attempt < 200; attempt++) {
    const response = await fetch('http://127.0.0.1:' + state.port + '/api/snapshot', {headers: {Authorization: 'Bearer ' + process.env.COMMANDO_TOKEN}});
    registered = response.ok && (await response.json()).panes.some(pane => pane.id === state.pane && pane.command === path.basename(process.execPath) && !pane.dead);
    if (registered) break;
    await new Promise(resolve => setTimeout(resolve, 25));
  }
  if (!registered) throw new Error('Fixture pane was not registered');
hook('sessionStart');
hook('beforeSubmitPrompt', {prompt: state.argv.at(-1)});
// Two opaque native IDs must remain distinct through hashing. Completing the
// first tool must not accidentally complete the other running activity.
hook('preToolUse', {tool_name: 'Shell', tool_use_id: 'synthetic/check opaque', tool_input: {command: 'npm test'}});
hook('preToolUse', {tool_name: 'Read', tool_use_id: 'synthetic/read opaque', tool_input: {file_path: 'fixture.txt'}});
// Cursor is responsible for pinning the context's resume instruction; this fake
// CLI follows that instruction through the real generated worklog executable.
execFileSync(process.execPath, [path.join(home, '.commando/hooks/commando-session-update.mjs'), '--session', 'agent --resume=conv-synthetic-acceptance'], {stdio: 'pipe'});
process.stdin.setRawMode(true); process.stdin.resume();
let pending = '';
process.stdin.on('data', (chunk) => {
  const text = chunk.toString(); fs.appendFileSync(path.join(home, 'fixture-input.txt'), text);
  process.stdout.write(text); pending += text;
  while (/[\\r\\n]/.test(pending)) {
    const end = pending.search(/[\\r\\n]/); const line = pending.slice(0, end); pending = pending.slice(end + 1);
    if (line === 'complete') {
      hook('postToolUse', {tool_name: 'Shell', tool_use_id: 'synthetic/check opaque', tool_input: {command: 'npm test'}, tool_output: JSON.stringify({exitCode: 0})});
      hook('postToolUse', {tool_name: 'Read', tool_use_id: 'synthetic/read opaque', tool_input: {file_path: 'fixture.txt'}});
      hook('stop', {status: 'completed'});
      hook('afterAgentResponse', {text: 'Synthetic response preamble\\n🟢 Synthetic fixture completed\\nResponse body must not reach the recap'});
    } else if (line === 'cancel') {
      generation = 'gen-2'; hook('beforeSubmitPrompt', {prompt: 'Synthetic cancellation turn'});
      hook('afterAgentResponse', {text: '🟢 Misleading synthetic completion candidate'});
      hook('stop', {status: 'aborted'});
    } else { state.unexpectedSubmittedLine = line; save(); }
  }
});
}
main().catch(error => { console.error(error.message); process.exit(1); });
`, { mode: 0o755 })
    // Keep one harmless bootstrap shell alive so tmux existed before daemon start;
    // launch must override its stale port while keeping the isolated profiles.
    tmux('-f', '/dev/null', 'new-session', '-d', '-s', 'acceptance-bootstrap', '-c', home, '/bin/sh')
    tmux('set-environment', '-g', 'COMMANDO_PORT', '1')
    for (const key of ['HOME', 'XDG_CONFIG_HOME', 'CURSOR_CONFIG_DIR', 'CLAUDE_CONFIG_DIR', 'CODEX_HOME', 'COMMANDO_AGENT_HOOK_TOKEN_PATH']) {
      tmux('set-environment', '-g', key, join(root, `stale-${key.toLowerCase()}`))
    }
    start(['--import', 'tsx', 'server/index.ts'])
    start(['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(webPort)])
    await expect.poll(async () => { try { return (await snapshot()).panes.length } catch { return 0 } }, { timeout: 25_000 }).toBe(1)
    // Presentation is the only shared-daemon call: open our isolated URL beside
    // this agent pane, never navigate or operate an existing user session/tile.
    if (process.env.TMUX_PANE) {
      try {
        const origin = `http://127.0.0.1:${process.env.COMMANDO_PORT ?? '4310'}`
        const hookToken = (await readFile(process.env.COMMANDO_AGENT_HOOK_TOKEN_PATH ?? join(process.env.HOME!, '.commando/agent-hook-token'), 'utf8')).trim()
        const response = await fetch(`${origin}/api/web-panes`, {
          method: 'POST', headers: { Authorization: `Bearer ${hookToken}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: `${baseUrl}/#token=${token}`, anchor: process.env.TMUX_PANE, placement: 'auto', engine: 'webkit' }),
          signal: AbortSignal.timeout(5_000),
        })
        if (response.ok) {
          const result = await response.json()
          presentation = { id: result.webPaneId, origin, token: hookToken }
        } else console.log(`Isolated preview tile unavailable (${response.status})`)
      } catch { console.log('Isolated preview tile unavailable; acceptance continues headlessly') }
    }
    await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: baseUrl })
    // GitHub is an unrelated external dependency and no gh credentials/binary
    // are present in this sandbox. Keep its pane PR counts deterministically
    // empty; Cursor launch, native hooks, worklogs and terminal input stay real.
    await page.route(`${baseUrl}/api/prs/pane?*`, (route) => route.fulfill({ json: { list: {
      targetId: new URL(route.request().url()).searchParams.get('paneId'),
      totalCount: 0, pullRequests: [], truncated: false, fetchedAt: Date.now(),
    } } }))
    page.on('pageerror', (error) => failures.push(error.message))
    page.on('console', (message) => { if (message.type() === 'error') failures.push(message.text()) })
    page.on('websocket', (connection) => connection.on('framereceived', ({ payload }) => {
      try {
        const message = JSON.parse(String(payload))
        if (String(message.type).startsWith('agent_status')) {
          statusFrames.push(message)
          if (statusFrames.length > 30) statusFrames.shift()
        }
      } catch { /* Binary terminal frames are not status evidence. */ }
    }))
    await page.setViewportSize({ width: 1800, height: 1100 })
    await page.goto(`${baseUrl}/#token=${token}`)
    await page.locator('.tmux-create > summary').click()
    const form = page.locator('.tmux-create form')
    await expect(form.getByLabel('Start with')).toHaveValue('shell')
    await expect(form.getByLabel('Opening prompt')).toHaveCount(0)
    const prompt = "--force\nVerify Leo's literal $HOME; $(touch injected) and `touch injected`"
    await form.getByLabel('Session name', { exact: true }).fill('cursor-synthetic-acceptance')
    await form.getByRole('combobox', { name: /Working directory/ }).fill(cwd)
    await form.getByLabel('Start with').selectOption('cursor')
    await form.getByLabel('Opening prompt').fill(prompt)
    await expect(form.getByRole('button', { name: 'Create session', exact: true })).toBeEnabled()
    for (const [label, width] of [['wide', 1800], ['narrow', 820]] as const) {
      await page.setViewportSize({ width, height: 1100 })
      if (label === 'narrow') await page.getByRole('button', { name: 'Open session tree', exact: true }).click()
      for (const control of [form.getByLabel('Start with'), form.getByLabel('Opening prompt'), form.getByRole('button', { name: 'Create session', exact: true })]) await fitsViewport(control)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: join(shots, `cursor-${label}-launch.png`) })
    }
    await page.setViewportSize({ width: 1800, height: 1100 })
    const launched = page.waitForResponse((response) => response.url().endsWith('/api/tmux/sessions') && response.request().method() === 'POST')
    await form.getByRole('button', { name: 'Create session', exact: true }).click()
    const response = await launched
    expect(response.request().postDataJSON()).toMatchObject({ name: 'cursor-synthetic-acceptance', cwd, agent: { provider: 'cursor', prompt } })
    expect(response.ok()).toBe(true)
    const { created } = await response.json()
    await expect.poll(async () => { try { return (await fixtureState()).hooks.length } catch { return 0 } }).toBe(4)
    const state = await fixtureState()
    expect(state).toMatchObject({ stdinTTY: true, stdoutTTY: true, argv: ['agent', '--', prompt], pane: created.paneId, cwd,
      port: String(daemonPort), home, cursorProfile: env.CURSOR_CONFIG_DIR, claudeProfile: env.CLAUDE_CONFIG_DIR,
      codexProfile: env.CODEX_HOME, tokenPath: env.COMMANDO_AGENT_HOOK_TOKEN_PATH, socket })
    expect(execFileSync('/bin/ps', ['-p', String(state.pid), '-o', 'tty=,command='], { encoding: 'utf8' })).toContain(runtime)
    expect(Number(tmux('display-message', '-p', '-t', created.paneId, '#{pane_pid}'))).toBe(state.pid)
    expect(state.hooks[0].response.additional_context).toContain('agent --resume=conv-synthetic-acceptance')
    expect(state.hooks[1].response).toEqual({ continue: true })
    expect(state.hooks[2].response).toEqual({ permission: 'allow' })
    await expect(readFile(join(cwd, 'injected'))).rejects.toMatchObject({ code: 'ENOENT' })
    const hud = page.getByRole('button', { name: /^Open Cursor agent in pane/ })
    await expect(hud).toHaveAttribute('aria-label', /Status: working/)
    await expect(hud).toContainText('test running')
    await expect(page.locator('.managed-session-tree').getByRole('button', { name: /^Cursor: working/ })).toBeVisible()
    tmux('send-keys', '-t', created.paneId, '-l', 'complete')
    tmux('send-keys', '-t', created.paneId, 'Enter')
    await expect(hud).toContainText('Done')
    await expect(hud).toContainText('Synthetic fixture completed')
    await expect(hud).toContainText('test passed')
    await expect(hud).not.toContainText('Response body must not reach')
    await expect(hud).not.toContainText('Synthetic response preamble')
    const cursorStatuses = () => statusFrames.map((message) => message.status)
      .filter((status): status is AgentStatus => status?.provider === 'cursor' && status.paneId === created.paneId)
    const pairedShellCompletion = cursorStatuses().find((status) => status.status === 'working' &&
      status.details?.checks?.some((check) => check.label === 'test' && check.status === 'passed') &&
      status.details.currentActivity?.label === 'Read file')
    expect(pairedShellCompletion, 'Completing the hashed Shell ID keeps the distinct Read ID running').toBeDefined()
    expect(cursorStatuses().some((status) => status.status === 'working' && !status.details?.currentActivity &&
      status.details?.recentActivities?.some((activity) => activity.label === 'Read file' && activity.state === 'completed'))).toBe(true)
    const completedStatuses = cursorStatuses().filter((status) => status.status === 'done')
    expect(completedStatuses.length).toBeGreaterThanOrEqual(2)
    const stopRecap = completedStatuses[0].details?.recap
    const correctedRecap = completedStatuses.at(-1)!.details?.recap
    expect(stopRecap?.summary).not.toBe('Synthetic fixture completed')
    expect(correctedRecap).toMatchObject({ summary: 'Synthetic fixture completed', completedAt: stopRecap?.completedAt })
    expect(JSON.stringify(cursorStatuses())).not.toMatch(/synthetic\/(?:check|read) opaque/)
    tmux('send-keys', '-t', created.paneId, '-l', 'cancel')
    tmux('send-keys', '-t', created.paneId, 'Enter')
    await expect(hud).toContainText('Cancelled')
    await expect(hud).toHaveAttribute('aria-label', /Status: unknown/)
    await expect(hud).not.toContainText('Misleading synthetic completion candidate')
    await expect(hud).not.toContainText('Done')
    const pane = page.locator(`[data-pane-id="${created.paneId}"]`)
    await pane.getByRole('button', { name: /^Expand worklog/ }).click()
    const resume = 'agent --resume=conv-synthetic-acceptance'
    await expect(pane.getByRole('button', { name: /Resume session/ })).toContainText(resume)
    await pane.getByRole('button', { name: 'Copy resume command', exact: true }).click()
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(resume)
    const beforeInput = await input()
    await pane.getByRole('button', { name: /Resume session/ }).click()
    await expect.poll(input).toBe(beforeInput + resume)
    expect((await fixtureState()).unexpectedSubmittedLine).toBeUndefined()
    for (const [label, width] of [['wide', 1800], ['narrow', 820]] as const) {
      await page.setViewportSize({ width, height: 1100 })
      if (label === 'narrow') {
        await page.locator('.session-sidebar').getByRole('button', { name: 'Hide session tree', exact: true }).click()
        await page.getByRole('button', { name: 'Open HUD', exact: true }).click()
        // Responsive drawers animate. Capture their final geometry, rather
        // than a source-faithful but misleading mid-transition clipped frame.
        await expect.poll(() => page.locator('.session-sidebar').evaluate((element) => element.getBoundingClientRect().right <= 1)).toBe(true)
        await expect.poll(() => page.locator('.agent-hud').evaluate((element) => {
          const box = element.getBoundingClientRect()
          return box.left >= 0 && box.right <= innerWidth + 1
        })).toBe(true)
      }
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: join(shots, `cursor-${label}-cancelled-resume.png`) })
      if (label === 'narrow') {
        await page.locator('.agent-hud').getByRole('button', { name: 'Hide HUD', exact: true }).click()
        await expect.poll(() => page.locator('.agent-hud').evaluate((element) => element.getBoundingClientRect().left >= innerWidth - 1)).toBe(true)
        await page.screenshot({ path: join(shots, 'cursor-narrow-resume-pane.png') })
      }
    }
    // Removing only the fake binary makes the real daemon resolver fail. There
    // is no real user CLI on the whitelist PATH and no second successful session.
    expect(failures).toEqual([])
    await rename(join(bin, 'agent'), join(bin, 'agent-unavailable'))
    await page.setViewportSize({ width: 1800, height: 1100 })
    await page.getByRole('button', { name: 'Show session tree', exact: true }).click()
    await form.getByLabel('Session name', { exact: true }).fill('cursor-missing-executable')
    await form.getByLabel('Start with').selectOption('cursor')
    const sessionsBefore = tmux('list-sessions', '-F', '#{session_id}:#{session_name}')
    const panesBefore = tmux('list-panes', '-a', '-F', '#{pane_id}')
    const missing = page.waitForResponse((reply) => reply.url().endsWith('/api/tmux/sessions') && reply.request().method() === 'POST')
    await form.getByRole('button', { name: 'Create session', exact: true }).click()
    const rejected = await missing
    expect(rejected.ok()).toBe(false)
    await expect(form.getByRole('alert')).toContainText('Cannot start agent: executable not found on the daemon PATH')
    await expect(form.getByRole('alert')).toContainText('Install the CLI on the daemon host')
    expect(tmux('list-sessions', '-F', '#{session_id}:#{session_name}')).toBe(sessionsBefore)
    expect(tmux('list-panes', '-a', '-F', '#{pane_id}')).toBe(panesBefore)
    expect((await fixtureState()).hooks.map((hook: { event: string }) => hook.event)).toEqual([
      'sessionStart', 'beforeSubmitPrompt', 'preToolUse', 'preToolUse', 'postToolUse', 'postToolUse', 'stop', 'afterAgentResponse',
      'beforeSubmitPrompt', 'afterAgentResponse', 'stop',
    ])
    await page.screenshot({ path: join(shots, 'cursor-missing-executable.png') })
    // Chromium reports expected failed HTTP requests as console.error; count
    // only that intentional negative acceptance request as an allowed failure.
    expect(failures.filter((message) => !/Failed to load resource.*status of 400/.test(message))).toEqual([])
    passed = true
  } catch (error) {
    await page.screenshot({ path: join(shots, 'cursor-failure.png') }).catch(() => undefined)
    await writeFile(join(root, 'child-stderr.json'), JSON.stringify(children.map((child) => ({
      pid: child.pid, exitCode: child.exitCode, signalCode: child.signalCode, stderr: childErrors.get(child) ?? '',
    })), null, 2))
    await writeFile(join(root, 'agent-status-frames.json'), JSON.stringify(statusFrames, null, 2))
    throw error
  } finally {
    if (presentation) {
      await fetch(`${presentation.origin}/api/web-panes/${presentation.id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${presentation.token}` }, signal: AbortSignal.timeout(5_000) }).catch(() => undefined)
    }
    await page.close()
    await Promise.all(children.map(stop))
    // This socket was created by this test. Never use the shared/default server.
    try { tmux('kill-server') } catch { /* Setup failure or already closed. */ }
    try {
      await writeFile(join(root, 'synthetic-fixture-state.json'), await readFile(join(home, 'fixture-state.json')))
      await writeFile(join(root, 'synthetic-fixture-input.txt'), await input())
      await writeFile(join(root, 'installed-cursor-bridge.mjs'), await readFile(join(home, '.commando/hooks/commando-cursor-agent-status.mjs')))
    } catch { /* Launch might not have reached the fixture. */ }
    await writeFile(join(root, 'acceptance-result.json'), JSON.stringify({ passed, screenshotDirectory: shots, daemonPort, webPort,
      childPids: children.map((child) => child.pid), tmuxBinary, socket, cleanedUp: true, synthetic: true }, null, 2))
    await testInfo.attach('cursor-acceptance-result', { path: join(root, 'acceptance-result.json'), contentType: 'application/json' })
    await rm(home, { recursive: true, force: true })
    await rm(bin, { recursive: true, force: true })
    await rm(cwd, { recursive: true, force: true })
    await rm(join(root, 'cursor-agent'), { recursive: true, force: true })
    console.log(`Cursor synthetic acceptance evidence: ${root}`)
  }
})
